spring:
  datasource:
    url:  "jdbc:postgresql://localhost:5432/postgres"
    username:  postgres
    password:  root

  application:
    name:  petstore

  logging:
    level:
      root: INFO
      com.example: DEBUG